@baseUrl = http://localhost:3333

# @name @createAccount
POST {{{baseUrl}}/accounts}
Content-Type: application/json

{
  "name": "Matheus Reinheimer",
  "email": "matheus.reinheimer",
  "password": "123456"
}